### ISSUE TITLE
React route transitions working for react-router-dom v4.1.1

### ISSUE THREAD

**Issue by Numel2020** [gpltaylor/react-router-workshop#1]
I tried to get the react route example working locally on my machine, but Webpack as issue with it, so I wanted to ask if your example is still compatible with the latest version of react Router.

**Comment by gpltaylor** [comment]
Hi @Numel2020 
I have just updated this to the latest version. This was running an alpha version of RRv4 as I have been working on the code base.

If you pull the latest code this will work now.

Let me know if this fixes your issues.

**Comment by gpltaylor** [comment]
fixed : https://github.com/gpltaylor/react-router-workshop/commit/db0c7a0d80376a17e37a8777855119580aadde64

Can you please confirm so I can close this issue.

**Comment by Numel2020** [comment]
Hi @gpltaylor 
So I Have managed to clone your repo and tested on my machine. It does not seem to be working correctly. To help you identify the issues I have setup some steps for you to follow so that you can verify the cases.

**Case 1**
1. Install and run the 04-transition folder
2. You will see the home page fadeIn as it should when its mounted
3. Click on About Us - You notice there is no transition
4. Click on Apply - You will notice there is no transition

**Case 2**
1. So click on Apply and refresh your page - notice that apply fades in
2. Click on the buttons in this order for testing - Apply => About Us => Home
repeat this clicking 10 times
3. You may notice transitions are working, but it is like it is bubbling the event?

I am going to be spending some time on this issue, I have done a bit a research into this over the last couple of weeks and I have fragments of code which you may better understand than myself and which may help.

**Testing rig**
Mac OS X el capitan.

**Comment by Numel2020** [comment]
Have a look at this article:

https://github.com/ReactTraining/react-router/issues/3936

This chap mentions a method like yours, his code may be of use to you.

**Comment by Numel2020** [comment]
Hi @gpltaylor 

This is Similar to what you are wanting to achieve but I not able to create a leave transition for the exiting component. This might give you some ideas?

http://codepen.io/w9914420/pen/LyEOaV

I need to do some further investigation

**Comment by Numel2020** [comment]
Hi @gpltaylor 

I have managed to get a step closer to what I think we need please see pen below

http://codepen.io/w9914420/pen/YVZEpz

In principle it uses params but the system should be able to do the same on a basic component,
The problem that it has is that it will play the transition on the component again if the same button is pressed.

**Comment by Numel2020** [comment]
Hi @gpltaylor 
I have the answer for now please have a look at the pen :)
[my pen](https://codepen.io/w9914420/pen/gRpPMZ)

I believe going forward that using switch seems to be the best way of doing this which addresses some of the issues I mentioned before.
